### PR TITLE
Set exit code to non-zero value on error, fix #42

### LINKED ISSUE #42: Shell cannot detect error
### Operating System (Linux (Docker)
Linux e2e4d9bfe136 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 GNU/Linux

### Expected Behavior
When `code-coverage` throws an error, a non-zero value should be returned to the calling process (such as the shell under Linux) so a pipeline can fail for instance.

### Actual Behavior

In case of any error, to the shell a zero "0" value is returned.

### Reproducible Test Case

Some use cases below.

~~~bash
# Try to invoke with non-existing lcov file...
$ cat my_non_existing_lcov.info | codacy-coverage
cat: coverage/lcov.info1: No such file or directory
[error] "2017-08-15T18:12:26.068Z"  { ValidationError: "value" is not allowed to be empty
    at Object.exports.process (/usr/local/lib/node_modules/codacy-coverage/node_modules/joi/lib/errors.js:140:17)
    at internals.String.internals.Any._validateWithOptions (/usr/local/lib/node_modules/codacy-coverage/node_modules/joi/lib/any.js:654:25)
    at module.exports.internals.Any.root.validate (/usr/local/lib/node_modules/codacy-coverage/node_modules/joi/lib/index.js:100:23)
    at /usr/local/lib/node_modules/codacy-coverage/lib/impl/lcov.js:11:37
...
$ echo $?
0

# Token incorrect
cat coverage/lcov.info | codacy-coverage
[error] "2017-08-15T18:13:51.688Z"  'Status Code [404] - Error [{"error":"not found"}]'
[error] "2017-08-15T18:13:51.691Z"  'Error sending coverage'
[error] "2017-08-15T18:13:51.691Z"  Error: Expected Successful Status Code, but got [404]
    at /usr/local/lib/node_modules/codacy-coverage/lib/reporter.js:101:23

$ echo $?
0

# Token not set in ENV
cat coverage/lcov.info | codacy-coverage
[error] "2017-08-15T18:14:25.391Z"  'Error sending coverage'
[error] "2017-08-15T18:14:25.393Z"  Error: Token is required

$ echo $?
0
 ~~~

### PR DESCRIPTION
**Pull request by bobisjan**

### CODE REVIEW

**Comment by rtfpessoa** [comment]
Hi @bobisjan, thanks for your contribution.
Seems like since you set the exit code the tests are exiting with it and failing.
Can you take a look? CircleCI should start in the next commit, but due to configurations it did not start in this one.

**Comment by bobisjan** [comment]
Hi @rtfpessoa,

it seems that all 39 tests are passing, the problem is with 2 vulnerabilities found (`moment` and `tough-cookie`), I think it should be handled by #46, then this can be merged.

I used `yarn test` locally, so I did not find this error until used `npm test`.

**Comment by rtfpessoa** [comment]
@bobisjan you are right. I missed that part.
The other PR is stale for a while need to check it with Joi 12 and see if it works.

**Comment by rtfpessoa** [comment]
@jere1862 please rebase with master to bring the version fixes.

**Comment by rtfpessoa** [comment]
@bobisjan please rebase with master to bring the fixes for the versions.

**Comment by bobisjan** [comment]
@rtfpessoa done.

**Comment by rtfpessoa** [comment]
Will be released as version `2.1.0`

**Pull request merged**
